import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - Orvantia AI",
  description: "Terms of Service for Orvantia AI products and services.",
};

export default function TermsPage() {
  return (
    <div
      className="relative w-full min-h-screen"
      style={{
        paddingTop: "clamp(120px, 15vw, 180px)",
        paddingBottom: "clamp(80px, 10vw, 120px)",
        paddingLeft: "clamp(24px, 5vw, 72px)",
        paddingRight: "clamp(24px, 5vw, 72px)",
        background: "var(--bg)",
      }}
    >
      <div className="absolute inset-0 grid-bg opacity-25 pointer-events-none" />
      
      <div className="relative z-10 max-w-3xl mx-auto">
        <div style={{ marginBottom: "clamp(48px, 8vw, 80px)" }}>
          <div
            style={{
              fontFamily: "var(--mono)",
              fontSize: 10,
              letterSpacing: "0.2em",
              color: "rgba(99,102,241,0.8)",
              textTransform: "uppercase",
              marginBottom: 16,
            }}
          >
            02 / Legal
          </div>
          <h1
            style={{
              fontFamily: "var(--font)",
              fontSize: "clamp(40px, 6vw, 64px)",
              fontWeight: 700,
              letterSpacing: "-0.03em",
              color: "rgba(241,245,249,0.95)",
              marginBottom: 24,
            }}
          >
            Terms of Service
          </h1>
          <p
            style={{
              fontFamily: "var(--font)",
              fontSize: "clamp(15px, 1.2vw, 18px)",
              color: "rgba(241,245,249,0.4)",
              lineHeight: 1.6,
            }}
          >
            Last Updated: June 2026
          </p>
        </div>

        <div
          className="glass-card"
          style={{
            padding: "clamp(32px, 5vw, 64px)",
            fontFamily: "var(--font)",
            fontSize: "15px",
            lineHeight: 1.8,
            color: "rgba(241,245,249,0.7)",
          }}
        >
          <section style={{ marginBottom: 40 }}>
            <h2 style={{ fontSize: 24, fontWeight: 600, color: "rgba(241,245,249,0.95)", marginBottom: 16 }}>
              1. Acceptance of Terms
            </h2>
            <p style={{ marginBottom: 16 }}>
              By accessing or using the autonomous AI products provided by Orvantia AI (including Continuum, Enteraflux, and ClinicalAgents), you agree to be bound by these Terms of Service. If you are entering into these terms on behalf of an enterprise or organization, you represent that you have the authority to bind such entity.
            </p>
          </section>

          <section style={{ marginBottom: 40 }}>
            <h2 style={{ fontSize: 24, fontWeight: 600, color: "rgba(241,245,249,0.95)", marginBottom: 16 }}>
              2. Use of Autonomous Products
            </h2>
            <p style={{ marginBottom: 16 }}>
              Our AI systems are designed to operate autonomously within the parameters established during integration. You agree to:
            </p>
            <ul style={{ listStyleType: "disc", paddingLeft: 20, marginBottom: 16, display: "flex", flexDirection: "column", gap: 8 }}>
              <li>Provide accurate configuration data and necessary access permissions (e.g., repository access for Continuum, compliance guardrails for ClinicalAgents).</li>
              <li>Not attempt to reverse-engineer, decompile, or otherwise extract the underlying neural mesh topologies or reasoning engines.</li>
              <li>Use the services strictly in accordance with applicable laws, particularly concerning healthcare data (HIPAA) and enterprise intellectual property.</li>
            </ul>
          </section>

          <section style={{ marginBottom: 40 }}>
            <h2 style={{ fontSize: 24, fontWeight: 600, color: "rgba(241,245,249,0.95)", marginBottom: 16 }}>
              3. Intellectual Property
            </h2>
            <p style={{ marginBottom: 16 }}>
              Orvantia AI retains all rights, title, and interest in and to our core technology, algorithms, and interface designs. Any code, insights, or structural changes generated by our agents (such as code written by Continuum) within your isolated environment become the property of your organization, subject to any open-source licenses applicable to dependencies.
            </p>
          </section>

          <section style={{ marginBottom: 40 }}>
            <h2 style={{ fontSize: 24, fontWeight: 600, color: "rgba(241,245,249,0.95)", marginBottom: 16 }}>
              4. Limitation of Liability
            </h2>
            <p style={{ marginBottom: 16 }}>
              While our systems maintain a 99.98% uptime and execute with extremely high confidence rates, Orvantia AI is not liable for indirect, incidental, or consequential damages arising from autonomous executions, workflow automation, or clinical data extraction errors. Enterprises are responsible for implementing final human-in-the-loop oversight where required by industry regulation.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
